"""Validated fixed-investment values for stochastic replay."""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import TYPE_CHECKING

import pandas as pd
import yaml

if TYPE_CHECKING:
    from zen_garden.model.element import Element


class FixedInvestments:
    """Read one complete power/energy investment policy from YAML or JSON."""

    def __init__(self, records: list[dict], valid_nodes: tuple[int, ...]):
        self._values: dict[tuple[str, str, str, int], float] = {}
        self._used: set[tuple[str, str, str, int]] = set()
        for record in records:
            if not isinstance(record, dict) or set(record) != {
                "technology",
                "capacity_type",
                "location",
                "node_id",
                "value",
            }:
                raise ValueError("Each fixed investment must have five named fields")
            technology = record["technology"]
            capacity_type = record["capacity_type"]
            location = record["location"]
            node_id = record["node_id"]
            value = record["value"]
            if (
                not isinstance(technology, str)
                or capacity_type not in ("power", "energy")
                or not isinstance(location, str)
                or type(node_id) is not int
                or node_id not in valid_nodes
                or isinstance(value, bool)
                or not isinstance(value, (int, float))
                or not math.isfinite(value)
                or value < 0
            ):
                raise ValueError(f"Invalid fixed investment: {record!r}")
            key = (technology, capacity_type, location, node_id)
            if key in self._values:
                raise ValueError(f"Duplicate fixed investment: {key}")
            self._values[key] = float(value)

    @classmethod
    def from_file(cls, path: str | Path, valid_nodes: tuple[int, ...]):
        """Read a policy generated by the expected-value solution."""
        path = Path(path)
        with path.open(encoding="utf-8") as stream:
            if path.suffix in {".yaml", ".yml"}:
                data = yaml.safe_load(stream)
            elif path.suffix == ".json":
                data = json.load(stream)
            else:
                raise ValueError(
                    f"Unsupported fixed-investment file type: {path.suffix}"
                )
        if (
            not isinstance(data, dict)
            or set(data) != {"investments"}
            or not isinstance(data["investments"], list)
        ):
            raise ValueError("Fixed-investment file needs an investments list")
        return cls(data["investments"], valid_nodes)

    def for_element(self, element: Element, capacity_type: str) -> pd.Series:
        """Return exactly one value per location and scenario-tree node."""
        location_set = element.location_type
        if location_set is None:
            raise ValueError(f"Technology {element.name} has no location set")
        index_values, index_names = element.element_data_loader.construct_index_list(
            [location_set, "set_years"]
        )
        index = pd.MultiIndex.from_product(index_values, names=index_names)
        values = []
        for location, node_id in index:
            key = (element.name, capacity_type, str(location), int(node_id))
            if key not in self._values:
                raise ValueError(f"Missing fixed investment: {key}")
            self._used.add(key)
            values.append(self._values[key])
        return pd.Series(values, index=index, dtype=float)

    def validate_consumed(self) -> None:
        """Reject unknown technologies, locations, and capacity types."""
        unused = self._values.keys() - self._used
        if unused:
            raise ValueError(f"Unexpected fixed investments: {sorted(unused)[:5]}")
